#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

# This script is known to work on Ubuntu 20.04 LTS and Ubuntu 21.10.
# Clover packages installed with this script will probably not work
# with Ubuntu 22.04 LTS as required dependencies would not be available
# in repositories. Official Ubuntu Clover packages may be usable
# with radeonsi as long as -cl-fast-relaxed-math is not enabled.
# See https://github.com/llvm/llvm-project/issues/54947
# Official Ubuntu Clover packages may not be usable with r600.
# See https://github.com/llvm/llvm-project/issues/54942

# Exit in case of failure.
set -e
set -o pipefail

# Error on undefined variable.
set -u

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

workspace_parent_dir='workspace'
workspace_dir="${workspace_parent_dir}/${script_name}"

tarball_referer='https://www.amd.com'
tarball_repo='https://drivers.amd.com/drivers/linux'

mesa_old_clover_opencl_deb_url_list='
http://archive.ubuntu.com/ubuntu/pool/main/l/llvm-toolchain-9/libllvm9_9.0.1-12_amd64.deb
http://archive.ubuntu.com/ubuntu/pool/universe/l/llvm-toolchain-9/libclang-common-9-dev_9.0.1-12_amd64.deb
http://archive.ubuntu.com/ubuntu/pool/universe/libc/libclc/libclc-dev_0.2.0+git20190827-4_all.deb
http://archive.ubuntu.com/ubuntu/pool/universe/libc/libclc/libclc-amdgcn_0.2.0+git20190827-4_all.deb
http://archive.ubuntu.com/ubuntu/pool/universe/libc/libclc/libclc-r600_0.2.0+git20190827-4_all.deb
http://archive.ubuntu.com/ubuntu/pool/universe/m/mesa/mesa-opencl-icd_20.0.4-2ubuntu1_amd64.deb
'

mesa_old_clover_opencl_deb_sum_list='
48bd8b89c9ca18b9360dbc04a65fea3d37b97664b4fc39202ff9006105f218dbab7fd7ce80c897e22c0e7b5e338317a361b54b726059ab74e6780e88c197b689  libllvm9_9.0.1-12_amd64.deb
18f5008921e7b1f52e0d91b07e170b22fca1a34899fc1d4d6e6ff8ed8f93137d88dc0aecc7631aac381e9e84f2c9bf54b2f0bdfa306d10d61f1380f42e53660f  libclang-common-9-dev_9.0.1-12_amd64.deb
800186922168ff3563a875adcd3f8084749858d64f37ffd044fbfa9f0625d466552afdbd1469f00ee6feb93b6bd33dae377c043df43d02678ae8c643f09560c5  libclc-dev_0.2.0+git20190827-4_all.deb
dc1510a5dd0cfbec431d046527dd11bcfc84c82a3fdd6d649781afb93a2af3a9dc28551a29024a5c7ae55b3457bd067481db3826cc0c931cd7f82881542d50d2  libclc-amdgcn_0.2.0+git20190827-4_all.deb
5680efd08badbbda9c7bd252890dd107fd4bf3399d0c73b5c685abd755419088a5c32d42ac419dd21f33968258937880782c1ae4129b9411b12aac9d531f85bc  libclc-r600_0.2.0+git20190827-4_all.deb
f276430f9f1d70d75692857dc7aa79365d6ef5dc1fd4ad816319e6f375e86f8eb29f49288d4f51d54da0f276712195fc217957c0e742696b338b91959bcd2e6e  mesa-opencl-icd_20.0.4-2ubuntu1_amd64.deb
'

fglrx_tarball_file="radeon-crimson-15.12-15.302-151217a-297685e.zip"
fglrx_tarball_sum='1658c3109e9dca2a1f0bd972e9042e7ccf17742e9c6110f04151334f342eb53d5a736b9cb63358a26d97562f1efb9e36c281bca85664e06f0cd11c275972f3af'
fglrx_tarball_dir='fglrx-15.302'
fglrx_script_file='amd-driver-installer-15.302-x86.x86_64.run'
fglrx_install_dir='/opt/amd-fglrx'

orca_tarball_file="amdgpu-pro-21.20-1271047-ubuntu-20.04.tar.xz"
orca_tarball_sum='530673e00c8e243e73e9322386f949c72d09c7f8f75f9760a4fad379d30a79c4562e79fc5eec9825adc1b8a396b23bda209182b7b457c2bce81c5c45500fb19b'
orca_deb_file_list='opencl-orca-amdgpu-pro-icd_21.20-1271047_amd64.deb'
orca_tarball_dir="$(basename "${orca_tarball_file}" '.tar.xz')"

pal_tarball_file="amdgpu-pro-20.40-1147286-ubuntu-20.04.tar.xz"
pal_tarball_sum='9b064a3b02d2a1ec18fdd6c098b70f4a8c6f93e4bfdc4e9a032ca387bdf7223278622c19d5bd55e493555c5f734168c3f2768cb743f9e00dcf5f96cbc399c7b3'
pal_deb_file_list='opencl-amdgpu-pro-comgr_20.40-1147286_amd64.deb opencl-amdgpu-pro-icd_20.40-1147286_amd64.deb'
pal_tarball_dir="$(basename "${pal_tarball_file}" '.tar.xz')"

rocm_version='5.7'
rocm_distro='jammy'

amdgpupro_deb_repo="https://repo.radeon.com/amdgpu-install/${rocm_version}/ubuntu/${rocm_distro}"

amdgpupro_deb_version='5.7.50700-1'
amdgpupro_deb_file="amdgpu-install_${amdgpupro_deb_version}_all.deb"
amdgpupro_deb_sum='190c5528385ee589130df94c902cd5a7f9f6877bd960d8009f5a55bb1c1552013187fd2c382c42819186ad162be9d838c65ef7e09fead3e1b5b991adc6a8daf4'

mesa_opencl_package_name_list='mesa-opencl-icd'
old_rocr_opencl_package_name_list='ocl-icd-libopencl1-amdgpu-pro'
rocr_opencl_package_name_list='rocm-opencl-runtime'
rocm_hip_package_name_list='rocm-hip-runtime rocminfo'
amdgpu_dkms_package_name_list='amdgpu-dkms'
amdgpu_mesa_opengl_package_name_list='libgl1-amdgpu-mesa-glx'
amdgpu_mesa_va_package_name_list='mesa-amdgpu-va-drivers'
amdgpu_mesa_vdpau_package_name_list='mesa-amdgpu-vdpau-drivers'
amdgpu_oglp_opengl_package_name_list='amdgpu-pro-oglp'

_error () {
	printf 'ERROR: %s\n\n' "${1}" >&2

	exit 1
}

is_mesa_old_clover_opencl='false'
is_mesa_clover_opencl='false'
is_fglrx_opencl='false'
is_orca_opencl='false'
is_pal_opencl='false'
is_rocr_opencl='false'
is_rocm_hip='false'
is_amdgpu_dkms='false'
is_amdgpu_mesa_opengl='false'
is_amdgpu_mesa_va='false'
is_amdgpu_mesa_vdpau='false'
is_amdgpu_oglp_opengl='false'

_is () {
	case "${1}" in
		'mesa-old-clover-opencl')
			"${is_mesa_old_clover_opencl}"
			;;
		'mesa-clover-opencl')
			"${is_mesa_clover_opencl}"
			;;
		'fglrx-opencl')
			"${is_fglrx_opencl}"
			;;
		'orca-opencl')
			"${is_orca_opencl}"
			;;
		'pal-opencl')
			"${is_pal_opencl}"
			;;
		'rocr-opencl')
			"${is_rocr_opencl}"
			;;
		'rocm-hip')
			"${is_rocm_hip}"
			;;
		'amdgpu-dkms')
			"${is_amdgpu_dkms}"
			;;
		'amdgpu-mesa-opengl')
			"${is_amdgpu_mesa_opengl}"
			;;
		'amdgpu-mesa-va')
			"${is_amdgpu_mesa_va}"
			;;
		'amdgpu-mesa-vdpau')
			"${is_amdgpu_mesa_vdpau}"
			;;
		'amdgpu-oglp-opengl')
			"${is_amdgpu_oglp_opengl}"
			;;
	esac
}

_checksum () {
	_cd

	case "${1}" in
		'old-clover')
			local IFS=$'\n'
			for package_sum_line in \
				$(echo "${mesa_old_clover_opencl_deb_sum_list}" | grep -v '^$')
			do
				sum="$(echo "${package_sum_line}" | awk '{ print $1 }')"
				file="$(echo "${package_sum_line}" | awk '{ print $2 }')"

				if [ -f "${file}" ]
				then
					if printf '%s %s\n' "${sum}" "${file}" \
						| sha512sum -c '/dev/stdin'
					then
						continue
					fi
				fi

				false
				return
			done

			return
			;;
		'fglrx')
			sum="${fglrx_tarball_sum}"
			file="${fglrx_tarball_file}"
			;;
		'amdgpupro')
			sum="${amdgpupro_deb_sum}"
			file="${amdgpupro_deb_file}"
			;;
		'orca')
			sum="${orca_tarball_sum}"
			file="${orca_tarball_file}"
			;;
		'pal')
			sum="${pal_tarball_sum}"
			file="${pal_tarball_file}"
			;;
	esac

	if [ -f "${file}" ]
	then
		if printf '%s %s\n' "${sum}" "${file}" \
			| sha512sum -c '/dev/stdin'
		then
			return
		fi
	fi

	false
}

_cd () {
	cd "${script_dir}"

	mkdir --parents --verbose "${workspace_dir}"

	cd "${workspace_dir}"
}

_download () {
	_cd

	if _is mesa-old-clover-opencl
	then
		if ! _checksum 'old-clover'
		then
			for mesa_old_clover_opencl_deb_url in \
				$(echo "${mesa_old_clover_opencl_deb_url_list}" | grep -v '^$' )
			do
				mesa_old_clover_opencl_package_file="$(echo "${mesa_old_clover_opencl_deb_url}" | sed -e 's|.*/||g' )"

				echo "Download ${mesa_old_clover_opencl_package_file}."

				rm -f "${mesa_old_clover_opencl_package_file}"

				wget "${mesa_old_clover_opencl_deb_url}"
			done

			_checksum 'old-clover'
		fi
	fi

	if _is fglrx-opencl
	then
		if ! _checksum 'fglrx'
		then
			echo "Download ${fglrx_tarball_file}."

			rm -f "${fglrx_tarball_file}"

			wget --header="Referer: ${tarball_referer}" \
				"${tarball_repo}/${fglrx_tarball_file}"

			_checksum 'fglrx'
		fi
	fi

	if _is orca-opencl || _is pal-opencl || _is rocr-opencl || _is rocm-hip
	then
		if ! _checksum 'amdgpupro'
		then
			echo "Download ${amdgpupro_deb_file}."

			rm -f "${amdgpupro_deb_file}"

			wget "${amdgpupro_deb_repo}/${amdgpupro_deb_file}"

			_checksum 'amdgpupro'
		fi
	fi

	if _is orca-opencl || _is pal-opencl
	then
		if ! _checksum 'orca'
		then
			echo "Download ${orca_tarball_file}."

			rm -f "${orca_tarball_file}"

			wget --header="Referer: ${tarball_referer}" \
				"${tarball_repo}/${orca_tarball_file}"

			_checksum 'orca'
		fi
	fi

	if _is pal-opencl
	then
		if ! _checksum 'pal'
		then
			echo "Download ${pal_tarball_file}."

			rm -f "${pal_tarball_file}"

			wget --header="Referer: ${tarball_referer}" \
				"${tarball_repo}/${pal_tarball_file}"

			_checksum 'pal'
		fi
	fi
}

_extract () {
	_cd

	_download

	if _is fglrx-opencl
	then
		if ! [ -d "${fglrx_tarball_dir}" ]
		then
			echo "Extract ${fglrx_tarball_file}."

			unzip "${fglrx_tarball_file}"
		fi
	fi

	if _is orca-opencl || _is pal-opencl
	then
		if ! [ -d "${orca_tarball_dir}" ]
		then
			echo "Extract ${orca_tarball_file}."

			tar --no-same-permissions -xvJf "${orca_tarball_file}"
		fi
	fi

	if _is pal-opencl
	then
		if ! [ -d "${pal_tarball_dir}" ]
		then
			echo "Extract ${pal_tarball_file}."

			tar --no-same-permissions -xvJf "${pal_tarball_file}"
		fi
	fi
}

_clean () {
	cd "${script_dir}"

	if [ -d "${workspace_dir}" ]
	then
		rm --force --verbose "${workspace_dir}/${fglrx_tarball_file}"
		rm --force --recursive --verbose "${workspace_dir}/${fglrx_tarball_dir}"

		rm --force --verbose "${workspace_dir}/${orca_tarball_file}"
		rm --force --recursive --verbose "${workspace_dir}/${orca_tarball_dir}"

		rm --force --verbose "${workspace_dir}/${pal_tarball_file}"
		rm --force --recursive --verbose "${workspace_dir}/${pal_tarball_dir}"

		rm --force --verbose "${workspace_dir}/${amdgpupro_deb_file}"

		rmdir --verbose "${workspace_dir}"
	fi

	if [ -d "${workspace_parent_dir}" ]
	then
		rmdir --ignore-fail-on-non-empty --verbose "${workspace_parent_dir}"
	fi
}

_purge () {
	case "${1}" in
		'mesa-old-clover-opencl')
			for mesa_old_clover_opencl_deb_file in \
				$(echo "${mesa_old_clover_opencl_deb_sum_list}" | grep -v '^$' | awk '{ print $2 }' | tac)
			do
				local mesa_old_clover_opencl_package_name="$(echo "${mesa_old_clover_opencl_deb_file}" | cut -f1 -d'_' )"

				apt-mark unhold "${mesa_old_clover_opencl_package_name}" || true

				apt-get remove --yes --purge "${mesa_old_clover_opencl_package_name}" || true
			done
			;;
		'mesa-clover-opencl')
			for mesa_clover_opencl_package_name in \
				$(echo "${mesa_clover_opencl_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${mesa_clover_opencl_package_name}" || true
			done
			;;
		'fglrx-opencl')
			rm --force --verbose \
				"${fglrx_install_dir}/x86_64-linux-gnu/libamdocl64-fglrx.so"
			rm --force --verbose \
				"${fglrx_install_dir}/x86_64-linux-gnu/libfglocl12cl64.so"

			if [ -d "${fglrx_install_dir}/x86_64-linux-gnu" ]
			then
				rmdir --ignore-fail-on-non-empty --verbose \
					"${fglrx_install_dir}/x86_64-linux-gnu"
			fi

			if [ -d "${fglrx_install_dir}" ]
			then
				rmdir --ignore-fail-on-non-empty --verbose \
					"${fglrx_install_dir}"
			fi

			rm --force --verbose \
				'/etc/ld.so.conf.d/30-amd-fglrx.conf'
			rm --force --verbose \
				'/etc/OpenCL/vendors/amdocl-fglrx64.icd'
			;;
		'orca-opencl')
			for orca_deb_file in \
				$(echo "${orca_deb_file_list}" | tr ' ' '\n' | tac)
			do
				local orca_package_name="$(echo "${orca_deb_file}" | cut -f1 -d'_')"

				apt-get remove --yes --purge "${orca_package_name}" || true
			done

			# Alternate name for opencl-orca-amdgpu-pro-icd package.
			apt-get remove --yes --purge 'opencl-legacy-amdgpu-pro-icd' || true
			;;
		'pal-opencl')
			for pal_deb_file in \
				$(echo "${pal_deb_file_list}" | tr ' ' '\n' | tac)
			do
				local pal_package_name="$(echo "${pal_deb_file}" | cut -f1 -d'_')"

				apt-get remove --yes --purge "${pal_package_name}" || true
			done
			;;
		'rocr-opencl')
			for rocr_opencl_package_name in \
				$(echo "${old_rocr_opencl_package_name_list}" "${rocr_opencl_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${rocr_opencl_package_name}" || true
			done
			;;
		'rocm-hip')
			for rocm_hip_package_name in \
				$(echo "${rocm_hip_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${rocm_hip_package_name}" || true
			done
			;;
		'amdgpu-dkms')
			for amdgpu_dkms_package_name in \
				$(echo "${amdgpu_dkms_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${amdgpu_dkms_package_name}" || true
			done
			;;
		'amdgpu-mesa-opengl')
			for amdgpu_mesa_opengl_package_name in \
				$(echo "${amdgpu_mesa_opengl_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${amdgpu_mesa_opengl_package_name}" || true
			done
			;;
		'amdgpu-mesa-va')
			for amdgpu_mesa_va_package_name in \
				$(echo "${amdgpu_mesa_va_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${amdgpu_mesa_va_package_name}" || true
			done
			;;
		'amdgpu-mesa-vdpau')
			for amdgpu_mesa_vdpau_package_name in \
				$(echo "${amdgpu_mesa_vdpau_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${amdgpu_mesa_vdpau_package_name}" || true
			done
			;;
		'amdgpu-oglp-opengl')
			for amdgpu_oglp_opengl_package_name in \
				$(echo "${amdgpu_oglp_opengl_package_name_list}" | tr ' ' '\n' | tac)
			do
				apt-get remove --yes --purge "${amdgpu_oglp_opengl_package_name}" || true
			done
			;;
	esac
}

_uninstall () {
	_purge mesa-clover-opencl
	_purge mesa-old-clover-opencl
	_purge pal-opencl
	_purge orca-opencl
	_purge rocr-opencl
	_purge rocm-hip
	_purge amdgpu-dkms
	_purge amdgpu-mesa-opengl
	_purge amdgpu-oglp-opengl
	_purge fglrx-opencl

	dpkg-divert \
		--rename \
		--remove '/opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so' \

	rm --force --verbose '/etc/OpenCL/vendors/amdocl-pal64.icd'

	if test -f '/usr/bin/amdgpu-install'
	then
		echo 'Yes' | '/usr/bin/amdgpu-install' --uninstall
	fi

	amdgpupro_package_name="$(echo "${amdgpupro_deb_file}" | cut -f1 -d'_')"
	apt-get remove --yes --purge "${amdgpupro_package_name}" || true

	# Read changes from /etc/ld.so.conf.d folder.
	ldconfig
}

_install () {
	_extract

	if _is orca-opencl || _is pal-opencl
	then
		apt-get update

		echo "Download gdebi-core package."
		apt-get install -y 'gdebi-core'
	fi

	if _is orca-opencl || _is pal-opencl || _is rocr-opencl
	then
		echo "Install ${amdgpupro_deb_file} package."

		dpkg -i "${amdgpupro_deb_file}"

		sed -e 's/^#deb /deb /' -i '/etc/apt/sources.list.d/amdgpu-proprietary.list'
	fi

	if _is mesa-old-clover-opencl || _is orca-opencl || _is pal-opencl || _is rocr-opencl
	then
		apt-get update
	fi

	if _is mesa-clover-opencl
	then
		for mesa_clover_opencl_package_name in ${mesa_clover_opencl_package_name_list}
		do
			echo "Install ${mesa_clover_opencl_package_name} package."

			apt-get install --yes "${mesa_clover_opencl_package_name}"
		done
	fi

	if _is mesa-old-clover-opencl
	then
		for mesa_old_clover_opencl_deb_file in \
			$(echo "${mesa_old_clover_opencl_deb_sum_list}" | grep -v '^$' | awk '{ print $2 }')
		do
			mesa_old_clover_opencl_package_name="$(echo "${mesa_old_clover_opencl_deb_file}" | cut -f1 -d'_' )"

			echo "Install ${mesa_old_clover_opencl_package_name} package."

			gdebi --non-interactive "${mesa_old_clover_opencl_deb_file}"

			apt-mark hold "${mesa_old_clover_opencl_package_name}"
		done
	fi

	if _is fglrx-opencl
	then
		local fglrx_extract_prefix="${fglrx_tarball_dir}/prefix"

		if ! [ -d "${fglrx_extract_prefix}" ]
		then
			"${fglrx_tarball_dir}/${fglrx_script_file}" --extract "${fglrx_extract_prefix}"
		fi

		mkdir --parents --verbose "${fglrx_install_dir}"
		mkdir --parents --verbose "${fglrx_install_dir}/x86_64-linux-gnu"

		cp --archive --verbose \
			"${fglrx_extract_prefix}/arch/x86_64/usr/lib64/libamdocl64.so" \
			"${fglrx_install_dir}/x86_64-linux-gnu/libamdocl64-fglrx.so"

		cp --archive --verbose \
			"${fglrx_extract_prefix}/arch/x86_64/usr/lib64/libamdocl12cl64.so" \
			"${fglrx_install_dir}/x86_64-linux-gnu/libfglocl12cl64.so"

		sed -e 's/libamdocl12cl64.so/libfglocl12cl64.so/g' \
			-i "${fglrx_install_dir}/x86_64-linux-gnu/libamdocl64-fglrx.so"

		echo 'libamdocl64-fglrx.so' > '/etc/OpenCL/vendors/amdocl-fglrx64.icd'

		echo "${fglrx_install_dir}/x86_64-linux-gnu" \
			> '/etc/ld.so.conf.d/30-amd-fglrx.conf'
	fi

	if _is orca-opencl || _is pal-opencl
	then
		# Already correct:
		# /opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-orca64.so

		local orca_deb_file
		for orca_deb_file in ${orca_deb_file_list}
		do
			local orca_package_name="$(echo "${orca_deb_file}" | cut -f1 -d'_')"

			if _is orca-opencl || [ "${orca_package_name}" != 'opencl-orca-amdgpu-pro-icd' ]
			then
				echo "Install ${orca_deb_file} package."

				gdebi --non-interactive "${orca_tarball_dir}/${orca_deb_file}"
			fi

			if [ "${orca_package_name}" != 'opencl-orca-amdgpu-pro-icd' ]
			then
				apt-mark auto "${orca_package_name}"
			fi
		done

		# Already correct:
		# libamdocl-rocm64.so
		# /etc/OpenCL/vendors/amdocl-orca64.icd
	fi

	if _is pal-opencl
	then
		dpkg-divert \
			--divert '/opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl-pal64.so' \
			--rename '/opt/amdgpu-pro/lib/x86_64-linux-gnu/libamdocl64.so' \

		local pal_deb_file
		for pal_deb_file in ${pal_deb_file_list}
		do
			echo "Install ${pal_deb_file} package."

			gdebi --non-interactive "${pal_tarball_dir}/${pal_deb_file}"
		done

		rm --force --verbose '/etc/OpenCL/vendors/amdocl64.icd'

		echo 'libamdocl-pal64.so' > '/etc/OpenCL/vendors/amdocl-pal64.icd'
	fi

	if _is rocr-opencl
	then
		# Already correct (icd may be renamed):
		# /opt/rocm-4.5.1/opencl/lib/libamdocl64.so

		for rocr_opencl_package_name in ${rocr_opencl_package_name_list}
		do
			echo "Install ${rocr_opencl_package_name} package."

			apt-get install --yes "${rocr_opencl_package_name}"
		done

		# Already correct (icd may be renamed):
		# libamdocl64.so
		# /etc/OpenCL/vendors/amdocl64.icd
	fi

	if _is rocm-hip
	then
		for rocm_hip_package_name in ${rocm_hip_package_name_list}
		do
			echo "Install ${rocm_hip_package_name} package."

			apt-get install --yes "${rocm_hip_package_name}"
		done
	fi

	if _is amdgpu-dkms
	then
		for amdgpu_dkms_package_name in ${amdgpu_dkms_package_name_list}
		do
			echo "Install ${amdgpu_dkms_package_name} package."

			apt-get install --yes "${amdgpu_dkms_package_name}"
		done
	fi

	if _is amdgpu-mesa-opengl
	then
		for amdgpu_mesa_opengl_package_name in ${amdgpu_mesa_opengl_package_name_list}
		do
			echo "Install ${amdgpu_mesa_opengl_package_name} package."

			apt-get install --yes "${amdgpu_mesa_opengl_package_name}"
		done
	fi

	if _is amdgpu-mesa-va
	then
		for amdgpu_mesa_va_package_name in ${amdgpu_mesa_va_package_name_list}
		do
			echo "Install ${amdgpu_mesa_va_package_name} package."

			apt-get install --yes "${amdgpu_mesa_va_package_name}"
		done
	fi

	if _is amdgpu-mesa-vdpau
	then
		for amdgpu_mesa_vdpau_package_name in ${amdgpu_mesa_vdpau_package_name_list}
		do
			echo "Install ${amdgpu_mesa_vdpau_package_name} package."

			apt-get install --yes "${amdgpu_mesa_vdpau_package_name}"
		done
	fi

	if _is amdgpu-oglp-opengl
	then
		for amdgpu_oglp_opengl_package_name in ${amdgpu_oglp_opengl_package_name_list}
		do
			echo "Install ${amdgpu_oglp_opengl_package_name} package."

			apt-get install --yes "${amdgpu_oglp_opengl_package_name}"
		done
	fi

	# Read changes from /etc/ld.so.conf.d folder.
	ldconfig
}

tab=$'\t'

_mention () {
	cat <<-EOF
	This tool is provided by the I love compute! initiative.

	Always backup this script for future uninstallation, future versions
	of this script may not uninstall what was installed with this one.

	Always uninstall before upgrading to an higher version of the
	distribution you use.

	Support the effort to keep OpenCL working on Linux, if this script saved
	your life, you can make a donation, see:

	${tab}https://gitlab.com/illwieckz/i-love-compute#funding

	EOF
}

_help () {
	cat <<-EOF
	${script_name}: Download, install or uninstall OpenCL drivers for AMD GPUs and CPUs.

	Usage: ${script_name} [OPTION] [ACTION] [NAMES]

	Option:
	${tab}-h, --help
	${tab}${tab}Print this help.

	Actions:
	${tab}download
	${tab}${tab}Download files if needed by NAME.
	${tab}extract
	${tab}${tab}Download archives if needed by NAME.
	${tab}clean
	${tab}${tab}Clean-up download and extracted files for NAME.
	${tab}install
	${tab}${tab}Install NAME (default: clover).
	${tab}uninstall
	${tab}${tab}Uninstall all OpenCL drivers for AMD GPUs.

	Names:
	${tab}all
	${tab}${tab}All OpenCL drivers for AMD GPUs and CPUs.
	${tab}mesa-old-clover-opencl
	${tab}${tab}Mesa old Clover OpenCL for Terascale2+ and GCN+ GPUs.
	${tab}fglrx-opencl
	${tab}${tab}AMD APP fglrx OpenCL from Radeon Crimson for CPUs.
	${tab}orca-opencl
	${tab}${tab}AMD APP Orca OpenCL from AMDGPU-PRO for GCN1-3 GPUs.
	${tab}pal-opencl
	${tab}${tab}AMD APP PAL OpenCL from AMDGPU-PRO for GCN4+ GPUs.
	${tab}rocr-opencl
	${tab}${tab}AMD APP ROCm OpenCL for Radeon Pro GPUs.
	${tab}rocm-hip
	${tab}${tab}AMD APP ROCm HIP for Radeon Pro GPUs.
	${tab}amdgpu-dkms
	${tab}${tab}AMD amdgpu DKMS modules and firmwares.
	${tab}amdgpu-mesa-opengl
	${tab}${tab}AMD amdgpu Mesa OpenGL.
	${tab}amdgpu-mesa-va
	${tab}${tab}AMD amdgpu Mesa VA.
	${tab}amdgpu-mesa-vdpau
	${tab}${tab}AMD amdgpu Mesa VDPAU.
	${tab}amdgpu-oglp-opengl
	${tab}${tab}AMD amdgpu OGLP OpenGL.

	Examples:
	${tab}${script_name} install all

	${tab}${script_name} install orca-opencl pal-opencl rocr-opencl

	${tab}${script_name} uninstall

	EOF

	_mention

	exit
}

case "${1:-}" in
	'download'|'extract'|'clean'|'install'|'uninstall')
		action="${1}"
		;;
	'-h'|'--help'|'')
		_help
		;;
	'-'*|'--'*)
		_error 'Unknown option.'
		;;
	*)
		_error 'Unknown action.'
		;;
esac

shift

case "${action}" in
	'download'|'extract'|'clean'|'install')
		if [ -z "${1:-}" ]
		then
			is_mesa_old_clover_opencl='true'
		fi

		while ! [ -z "${1:-}" ]
		do
			case "${1}" in
				'all')
					is_mesa_old_clover_opencl='true'
					is_fglrx_opencl='true'
					is_orca_opencl='true'
					is_pal_opencl='true'
					is_rocr_opencl='true'
					is_rocm_hip='true'
					;;
				'mesa-old-clover-opencl')
					is_mesa_old_clover_opencl='true'
					;;
				'fglrx-opencl')
					is_fglrx_opencl='true'
					;;
				'orca-opencl')
					is_orca_opencl='true'
					;;
				'pal-opencl')
					is_pal_opencl='true'
					;;
				'rocr-opencl')
					is_rocr_opencl='true'
					;;
				'rocm-hip')
					is_rocm_hip='true'
					;;
				'amdgpu-dkms')
					is_amdgpu_dkms='true'
					;;
				'amdgpu-mesa-opengl')
					is_amdgpu_mesa_opengl='true'
					;;
				'amdgpu-mesa-va')
					is_amdgpu_mesa_va='true'
					;;
				'amdgpu-mesa-vdpau')
					is_amdgpu_mesa_vdpau='true'
					;;
				'amdgpu-oglp-opengl')
					is_amdgpu_oglp_opengl='true'
					;;
				*)
					_error 'Unkown name.'
					;;
			esac

			shift
		done
		;;
esac

"_${action}"

printf '\n'

_mention
