#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2020 Thomas “illwieckz“ Debesse

set -e

tab=$'\t'

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"
workspace_dir="workspace/${script_name}"

tarball_version='21.20-1271047'
ubuntu_version='20.04'
tarball_sum='530673e00c8e243e73e9322386f949c72d09c7f8f75f9760a4fad379d30a79c4562e79fc5eec9825adc1b8a396b23bda209182b7b457c2bce81c5c45500fb19b'

tarball_repo='https://drivers.amd.com/drivers/linux'
tarball_file="amdgpu-pro-${tarball_version}-ubuntu-${ubuntu_version}.tar.xz"
tarball_dir="$(basename "${tarball_file}" '.tar.xz')"

deb_version='21.40.1.40501-1'
deb_sum='2dc31efa27e8ecd940dc46d6b30d99cbf2381724102e08995a14021b29598e9d0b76abcd7f13f426b0659bfccd20672ddea9b8266e540ce6161ced4c50079f3b'

deb_repo='https://repo.radeon.com/amdgpu-install/21.40.1/ubuntu/focal'
deb_file="amdgpu-install_${deb_version}_all.deb"

printSums () {
	cat <<-EOF
	${tarball_sum} ${tarball_file}
	${deb_sum} ${deb_file}
	EOF
}

cdWorkspace () {
	cd "${script_dir}"

	mkdir --parents --verbose "${workspace_dir}"
	cd "${workspace_dir}"
}

_download () {
	cdWorkspace

	if [ -f "${tarball_file}" ]
	then
		if printSums | sha512sum -c /dev/stdin
		then
			return
		fi
	fi

	echo "download ${tarball_file}"
	wget --continue \
		--header="Referer: https://www.amd.com" \
		"${tarball_repo}/${tarball_file}"

	echo "download ${deb_file}"
	wget --continue \
		"${deb_repo}/${deb_file}"
}

_extract () {
	cdWorkspace

	_download

	if ! [ -d "${tarball_dir}" ]
	then
		echo "extract ${tarball_file}"
		tar --no-same-permissions -xvJf "${tarball_file}"
	fi
}

_clean () {
	cd "${script_dir}"
	if [ -d "${workspace_dir}" ]
	then
		rm --verbose "${workspace_dir}/${tarball_file}"
		rm -r --verbose "${workspace_dir}/${tarball_dir}"
		rm --verbose "${workspace_dir}/${deb_file}"
		rmdir --verbose "${workspace_dir}"
	fi
}

_uninstall () {
	if test -f '/usr/bin/amdgpu-uninstall'
	then
		echo 'Yes' | '/usr/bin/amdgpu-uninstall'
	fi
}

_install () {
	_extract

	_uninstall

	apt-get update
	apt-get install -y 'gdebi-core'

	dpkg -i "${deb_file}"
	sed -e 's/^#deb /deb /' -i '/etc/apt/sources.list.d/amdgpu-proprietary.list'

	apt-get update
	dpkg --purge 'opencl-orca-amdgpu-pro-icd' 'opencl-legacy-amdgpu-pro-icd'

	gdebi -n "${tarball_dir}/opencl-orca-amdgpu-pro-icd_21.20-1271047_amd64.deb"
}

failure='false'

_help () {
	cat <<-EOF
	Usage: ${script_name} [ACTION] [OPTION]

	ACTION:
	${tab}download
	${tab}extract
	${tab}clean
	${tab}install
	${tab}uninstall
	EOF

	! "${failure}"

	exit
}

_error () {
	failure='true'
	_help
}

action='error'

while ! [ -z "${1}" ]
do
	case "${1}" in
		'download'|'extract'|'clean'|'install'|'uninstall')
			if [ "${action}" = 'error' ]
			then
				action="${1}"
			else
				_error
			fi
			;;
		'-h'|'--help')
			action='help'
			break
			;;
		*)
			_error
			;;
	esac

	shift
done

_${action}
