#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='clvk'
required_file='/libOpenCL.so'
help_preset='basic_platform'
build_preset='basic_project'
provides_opencl='true'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'clvk'
		'clvk'
		'https://github.com/kpet/clvk.git'
		'-'
		'clvk'
)

_set_custom_env () {
	export LD_LIBRARY_PATH="${install_dir}:${LD_LIBRARY_PATH:-}"
}

_build_clvk () {
	"${workspace_dir}/clvk/external/clspv/utils/fetch_sources.py"

	_build_generic_cmake
}

_help_custom_run () {
	cat <<-EOF
	${tab}${script_name} run clinfo --list

	${tab}AMD_VULKAN_ICD=AMDVLK ${script_name} run clinfo --list

	${tab}AMD_VULKAN_ICD=RADV ${script_name} run clinfo --list
	EOF
}

_spawn "${@}"
