#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

# You may need to install:
# libboost-chrono-dev libboost-date-time-dev libboost-system-dev libboost-thread-dev libqt5webkit5-dev libarchive-dev

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='ViennaCLBench'
required_file='/bin/ViennaCLBench'
help_preset='basic_application'
build_preset='basic_project'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'ViennaCL Benchmark'
		'viennaclbench-dev'
		'https://github.com/viennacl/viennaclbench-dev.git'
		'-'
		'generic_cmake'
)

# HACK, replace pull function
_pull () {
	if "${do_pull}"
	then
		git pull || true

		if grep -q 'USE_QT5' 'CMakeLists.txt'
		then
			git remote add illwieckz 'https://github.com/illwieckz/viennaclbench-dev.git'
			git fetch illwieckz
			git checkout fixes
		fi

		git submodule update --init --recursive

		{
			if [ "$(basename "$(pwd)")" = 'viennaclbench-dev' ]
			then
				if [ -d 'external' ]
				then
					cd 'external'

					if [ -f 'libarchive/README.md' ]
					then
						cd 'libarchive'
						git pull
					else
						git clone 'https://github.com/libarchive/libarchive.git'
					fi
				fi
			fi
		}
	fi
}

_help_custom_run () {
	cat <<-EOF
	${tab}${script_name} run viennaclbench
	EOF
}

_spawn "${@}"
