#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='piglit'
required_file='/bin/piglit'
help_preset='basic_platform'
build_preset='basic_project'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'waffle'
		'waffle'
		'https://gitlab.freedesktop.org/mesa/waffle.git'
		'-'
		'generic_cmake'
	'piglit'
		'piglit'
		'https://gitlab.freedesktop.org/mesa/piglit.git'
		'-'
		'piglit'
)

_build_piglit () {
	_cmake_setup \
		-D'PIGLIT_BUILD_CL_TESTS'='ON'

	_cmake_compile_install
}

_help_custom_run () {
	cat <<-EOF
	${tab}${script_name} run piglit run quick_cl /tmp/results/cl

	${tab}${script_name} run piglit run gpu /tmp/results/gpu

	${tab}${script_name} run piglit run quick_cl gpu /tmp/results/cl-gpu
	EOF
}

_spawn "${@}"
