#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='amdocl-fix'
required_file='/lib/amdocl_fix.so'
help_preset='basic_platform'
build_preset='basic_project'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'amdocl-fix'
		'resolve-amdocl-fix'
		'https://github.com/h33p/resolve-amdocl-fix.git'
		'-'
		'amdocl_fix'
)

_build_amdocl_fix () {
	make -j"${usable_job_count}"

	mkdir -pv "${install_dir}/lib"

	cp -av 'amdocl_fix.so' "${install_dir}${required_file}"
}

_set_custom_run_env () {
	export LD_PRELOAD="${install_dir}${required_file}:${LD_PRELOAD:-}"
}

_help_custom_run () {
	cat <<-EOF
	${tab}${script_name} run resolve
	EOF
}

_spawn "${@}"
