#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

# You may need to install:
# clang python3-setuptools python3-mako cmake meson doxygen libexpat1-dev libxml2-dev xsltproc xmlto libvulkan-dev libelf-dev byacc bison flex libxcb-glx0-dev libxcb-shm0-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxshmfence-dev libvdpau-dev libxvmc-dev libva-dev glslang-tools

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='Mold'
required_file='/bin/mold'
help_preset='basic_platform'
build_preset='basic_project'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'Mold'
		'mold'
		'https://github.com/rui314/mold.git'
		'-'
		'mold'
)

_build_mold () {
	local without_mold='1'

	_build_generic_cmake
}

_set_custom_run_env () {
	export MOLD='mold'
}

_help_custom_run () {
	cat <<-EOF

	${tab}${script_name} run gcc
	EOF
}

_spawn "${@}"
