#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

# You may need to install:
# build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-12-dev clang-12 llvm-12 make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='PoCL Clspv'
required_file='/etc/OpenCL/vendors/pocl.icd'
help_preset='basic_platform'
build_preset='basic_project'
provides_opencl='true'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'clspv'
		'clspv'
		'https://github.com/google/clspv.git'
		'-'
		'clspv'
	'PoCL'
		'pocl'
		'https://github.com/pocl/pocl.git'
		'-'
		'pocl'
)

_build_clspv () {
	python 'utils/fetch_sources.py'

	_cmake_setup \
		-D'CLSPV_BUILD_TESTS'='OFF' \

	_cmake_compile_install
}

_build_pocl () {
	_cmake_setup \
		-D'ENABLE_VULKAN'='ON' \
#		-D'ENABLE_EXPERIMENTAL_DRIVERS'='ON' \
#		-D'CLSPV_DIR'="${install_dir}/bin"

	_cmake_compile_install
}

_spawn "${@}"
