#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

# You may need to install:
# clang python3-setuptools python3-mako cmake meson doxygen libexpat1-dev libxml2-dev xsltproc xmlto libvulkan-dev libelf-dev byacc bison flex libxcb-glx0-dev libxcb-shm0-dev libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxshmfence-dev libvdpau-dev libxvmc-dev libva-dev glslang-tools

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='Mesa'
required_file='/lib/x86_64-linux-gnu/libvulkan_nouveau.so'
help_preset='basic_platform'
build_preset='basic_project'
provides_vulkan='true'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'Nvk'
		'mesa'
		'https://gitlab.freedesktop.org/nouveau/mesa.git'
		'nvk/main'
		'mesa'
)

_build_mesa () {
	local mesa_egl='disabled'
	local mesa_gbm='disabled'
	local mesa_glx='disabled'
	local mesa_glx_direct='false'
	local mesa_gles1='disabled'
	local mesa_gles2='disabled'
	local mesa_glvnd='false'
	local mesa_opengl='false'
	local mesa_gallium_nine='false'
	local mesa_gallium_opencl='disabled'
	local mesa_gallium_rusticl='false'
	local mesa_gallium_va='disabled'
	local mesa_gallium_vdpau='disabled'
	local mesa_gallium_xa='disabled'
	local mesa_gallium_xvmc='disabled'
	local mesa_opencl_spirv='false'
	local mesa_gallium_drivers=''
	local mesa_vulkan_beta='false'
	local mesa_vulkan_drivers=''
	local mesa_vulkan_rt_drivers=''
	local mesa_intel_clc='disabled'
	local mesa_llvm='disabled'
	local mesa_shared_llvm='disabled'

	# mesa_vulkan_beta='true'
	mesa_vulkan_drivers='nouveau-experimental'

	# See user-mesa for references about those options.
	# The list of options must be kept in sync even if
	# the features are not used or disabled reduce the
	# diff noise between the twos.
	_meson_setup \
		-D'cpp_rtti'='true' \
		-D'rust_std'='2021' \
		-D'dri-drivers'='[]' \
		-D'dri3'='enabled' \
		-D'egl'="${mesa_egl}" \
		-D'gbm'="${mesa_gbm}" \
		-D'glx'="${mesa_glx}" \
		-D'glx-direct'="${mesa_glx_direct}" \
		-D'gallium-drivers'="${mesa_gallium_drivers}" \
		-D'gallium-nine'="${mesa_gallium_nine}" \
		-D'gallium-omx'='disabled' \
		-D'gallium-opencl'="${mesa_gallium_opencl}" \
		-D'gallium-rusticl'="${mesa_gallium_rusticl}" \
		-D'gallium-va'="${mesa_gallium_va}" \
		-D'gallium-vdpau'="${mesa_gallium_vdpau}" \
		-D'gallium-xa'="${mesa_gallium_xa}" \
		-D'gallium-xvmc'="${mesa_gallium_xvmc}" \
		-D'opencl-spirv'="${mesa_opencl_spirv}" \
		-D'opengl'="${mesa_opengl}" \
		-D'glvnd'="${mesa_glvnd}" \
		-D'gles1'="${mesa_gles1}" \
		-D'gles2'="${mesa_gles2}" \
		-D'vulkan-drivers'="${mesa_vulkan_drivers}" \
		-D'vulkan-rt-drivers'="${mesa_vulkan_rt_drivers}" \
		-D'vulkan-beta'="${mesa_vulkan_beta}" \
		-D'intel-clc'="${mesa_intel_clc}" \
		-D'shader-cache'='true' \
		-D'platforms'='auto' \
		-D'llvm'="${mesa_llvm}" \
		-D'shared-llvm'="${mesa_shared_llvm}" \
		-D'lmsensors'='disabled'

	_meson_compile_install
}

_spawn "${@}"
