#! /usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright 2022 Thomas “illwieckz“ Debesse

# You may need to install:
# build-essential ocl-icd-libopencl1 cmake git pkg-config libclang-12-dev clang-12 llvm-12 make ninja-build ocl-icd-libopencl1 ocl-icd-dev ocl-icd-opencl-dev libhwloc-dev zlib1g zlib1g-dev clinfo dialog apt-utils

script_dir="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
script_name="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

. "${script_dir}/include.common.sh"

project_name='PoCL'
required_file='/etc/OpenCL/vendors/pocl.icd'
help_preset='basic_platform'
build_preset='basic_project'
provides_opencl='true'

packages=(
	# package name
	#	directory name
	#	repository url
	#	branch name
	#	build slug
	'PoCL'
		'pocl'
		'https://github.com/pocl/pocl.git'
		'-'
		'generic_cmake'
)

_spawn "${@}"
